apiVersion: pdok.nl/v1
kind: OwnerInfo
metadata:
  name: pdok
  labels:
    app.kubernetes.io/name: smooth-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  metadataUrls:
    csw:
      hrefTemplate: "https://www.nationaalgeoregister.nl/geonetwork/srv/dut/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.isotc211.org/2005/gmd&elementsetname=full&id={{identifier}}"
      type:
    opensearch:
      hrefTemplate: "https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/{{identifier}}/OpenSearchDescription.xml"
      type:
    html:
      hrefTemplate: "https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/{{identifier}}"
      type:
  namespaceTemplate: "http://{{prefix}}.geonovum.nl"
  atom:
    author: # author/owner van de dataset
      name: pdok
      email: pdokbeheer@kadaster.nl
  wfs:
    serviceprovider:
      providername: PDOK
      providersite:
        type: simple
        href: https://pdok.nl
      servicecontact:
        individualname: KlantContactCenter PDOK
        positionname: pointOfContact
        contactinfo:
          phone:
            voice:
            facsmile:
          text:
          address:
            deliverypoint:
            city: Apeldoorn
            administrativearea:
            postalcode:
            country: Netherlands
            electronicmailaddress: BeheerPDOK@kadaster.nl
          onlineresource:
            type:
            href:
          hoursofservice:
          contactinstructions:
        role:
  wms:
    contactinformation:
      contactpersonprimary:
        contactperson: KlantContactCenter PDOK
        contactorganization: PDOK
      contactposition: pointOfContact
      contactaddress:
        addresstype:
        address:
        city: Apeldoorn
        stateorprovince:
        postalcode:
        country: Netherlands
      contactvoicetelephone:
      contactfacsimiletelephone:
      contactelectronicmailaddress: BeheerPDOK@kadaster.nl