apiVersion: pdok.nl/v1
kind: OwnerInfo
metadata:
  name: pdok
  labels:
    app.kubernetes.io/name: smooth-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  metadataUrls:
    csw:
      hrefTemplate: "https://www.nationaalgeoregister.nl/geonetwork/srv/dut/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.isotc211.org/2005/gmd&elementsetname=full&id={{identifier}}"
      type: alternate
    openSearch:
      hrefTemplate: "https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/{{identifier}}/OpenSearchDescription.xml"
      type: alternate
    html:
      hrefTemplate: "https://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/{{identifier}}"
      type: alternate
  namespaceTemplate: "http://{{prefix}}.geonovum.nl"
  atom:
    defaultStylesheet: https://service.pdok.nl/atom/style/style.xsl
    author: # author/owner van de dataset
      name: pdok
      email: pdokbeheer@kadaster.nl
  providerSite:
    type: simple
    href: https://pdok.nl
  wfs:
    serviceProvider:
      providerName: PDOK
      serviceContact:
        individualName: KlantContactCenter PDOK
        positionName: pointOfContact
        contactInfo:
          phone:
            voice:
            facsimile:
          text:
          address:
            deliveryPoint:
            city: Apeldoorn
            administrativeArea:
            postalCode:
            country: Netherlands
            electronicMailAddress: BeheerPDOK@kadaster.nl
          onlineResource:
            type:
            href:
          hoursOfService:
          contactInstructions:
        role:
  wms:
    contactInformation:
      contactPersonPrimary:
        contactPerson: KlantContactCenter PDOK
        contactOrganization: PDOK
      contactPosition: pointOfContact
      contactAddress:
        addressType:
        address:
        city: Apeldoorn
        stateOrProvince:
        postCode:
        country: Netherlands
      contactVoiceTelephone:
      contactFacsimileTelephone:
      contactElectronicMailAddress: BeheerPDOK@kadaster.nl